"""
Kanibus - Complete Eye-Tracking ControlNet System for ComfyUI
==============================================================

A comprehensive neural system for video eye-tracking with ControlNet integration,
supporting WAN 2.1/2.2 models with multi-modal control generation.

Author: Generated by Claude Flow Hive Mind
Version: 1.0.0
License: MIT
"""

from .nodes import *

# Node class mappings for ComfyUI registration
NODE_CLASS_MAPPINGS = {
    "KanibusMaster": KanibusMaster,
    "VideoFrameLoader": VideoFrameLoader,
    "NeuralPupilTracker": NeuralPupilTracker,
    "AdvancedTrackingPro": AdvancedTrackingPro,
    "SmartFacialMasking": SmartFacialMasking,
    "AIDepthControl": AIDepthControl,
    "NormalMapGenerator": NormalMapGenerator,
    "LandmarkPro468": LandmarkPro468,
    "EmotionAnalyzer": EmotionAnalyzer,
    "HandTracking": HandTracking,
    "BodyPoseEstimator": BodyPoseEstimator,
    "ObjectSegmentation": ObjectSegmentation,
    "TemporalSmoother": TemporalSmoother,
    "MultiControlNetApply": MultiControlNetApply,
}

# Display names for ComfyUI interface
NODE_DISPLAY_NAME_MAPPINGS = {
    "KanibusMaster": "🧠 Kanibus Master",
    "VideoFrameLoader": "🎬 Video Frame Loader",
    "NeuralPupilTracker": "👁️ Neural Pupil Tracker",
    "AdvancedTrackingPro": "🎯 Advanced Tracking Pro",
    "SmartFacialMasking": "😷 Smart Facial Masking",
    "AIDepthControl": "🌊 AI Depth Control",
    "NormalMapGenerator": "🗺️ Normal Map Generator",
    "LandmarkPro468": "📍 Landmark Pro 468",
    "EmotionAnalyzer": "😊 Emotion Analyzer",
    "HandTracking": "✋ Hand Tracking",
    "BodyPoseEstimator": "🏃 Body Pose Estimator",
    "ObjectSegmentation": "✂️ Object Segmentation",
    "TemporalSmoother": "🔄 Temporal Smoother",
    "MultiControlNetApply": "🎛️ Multi-ControlNet Apply",
}

# Export version and info
__version__ = "1.0.0"
__author__ = "Claude Flow Hive Mind"
__description__ = "Complete Eye-Tracking ControlNet System for ComfyUI"

print(f"🐝 Kanibus v{__version__} - Eye-Tracking ControlNet System Loaded")
print("💫 Features: 14 nodes, GPU optimization, WAN 2.1/2.2 support")